apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.registryCtl" . }}"
  namespace: {{ include "harbor.namespace" . | quote }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
data:
  {{- template "harbor.traceEnvsForRegistryCtl" . }}
